import 'package:yaml/yaml.dart';

class AdminModel {
  const AdminModel({
    required this.className,
    required this.fields,
    this.tableName,
  });

  final String className;
  final String? tableName;
  final List<AdminField> fields;

  String get variableName => _lowerFirst(className);
  String get title => _pluralize(_splitWords(className));
  String get routeName => '/admin/${_kebabCase(_pluralize(className))}';
}

class AdminField {
  const AdminField({required this.name, required this.rawType});

  final String name;
  final String rawType;

  String get dartType => rawType.replaceAll('?', '').trim();
  bool get isNullable => rawType.trim().endsWith('?');
  String get label => _splitWords(name);

  AdminFieldKind get kind {
    return switch (dartType) {
      'String' => AdminFieldKind.text,
      'int' => AdminFieldKind.integer,
      'double' => AdminFieldKind.decimal,
      'bool' => AdminFieldKind.boolean,
      'DateTime' => AdminFieldKind.dateTime,
      _ => AdminFieldKind.unsupported,
    };
  }
}

enum AdminFieldKind { text, integer, decimal, boolean, dateTime, unsupported }

class AdminGenerator {
  const AdminGenerator();

  AdminModel parseModel(String yamlSource) {
    final document = loadYaml(yamlSource);
    if (document is! YamlMap) {
      throw const FormatException('Model YAML must be a map.');
    }

    final className = document['class'];
    if (className is! String || className.trim().isEmpty) {
      throw const FormatException('Model YAML must contain a class name.');
    }

    final fieldsNode = document['fields'];
    if (fieldsNode is! YamlMap || fieldsNode.isEmpty) {
      throw const FormatException('Model YAML must contain fields.');
    }

    final fields = <AdminField>[];
    for (final entry in fieldsNode.entries) {
      final name = entry.key;
      final type = entry.value;
      if (name is! String || name.trim().isEmpty) {
        throw const FormatException('Field names must be strings.');
      }
      if (type is! String || type.trim().isEmpty) {
        throw FormatException('Field "$name" must have a scalar type.');
      }
      fields.add(AdminField(name: name, rawType: type));
    }

    final tableName = document['table'];
    return AdminModel(
      className: className.trim(),
      tableName: tableName is String ? tableName.trim() : null,
      fields: fields,
    );
  }

  String generateFlutterSource(AdminModel model) {
    final buffer = StringBuffer()
      ..writeln(
        '// Generated by PocketPod admin generator. Do not edit by hand.',
      )
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln('class ${model.className}AdminScreen extends StatelessWidget {')
      ..writeln('  const ${model.className}AdminScreen({super.key});')
      ..writeln()
      ..writeln("  static const title = '${_escapeDart(model.title)}';")
      ..writeln("  static const routeName = '${_escapeDart(model.routeName)}';")
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Widget build(BuildContext context) {')
      ..writeln('    return Scaffold(')
      ..writeln('      appBar: AppBar(title: const Text(title)),')
      ..writeln('      body: ListView(')
      ..writeln('        padding: const EdgeInsets.all(24),')
      ..writeln('        children: const [')
      ..writeln('          _${model.className}Table(),')
      ..writeln('          SizedBox(height: 24),')
      ..writeln('          _${model.className}Form(),')
      ..writeln('        ],')
      ..writeln('      ),')
      ..writeln('    );')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..write(_generateTable(model))
      ..writeln()
      ..write(_generateForm(model));

    return buffer.toString();
  }

  String _generateTable(AdminModel model) {
    final columns = model.fields
        .map(
          (field) =>
              "          DataColumn(label: Text('${_escapeDart(field.label)}')),",
        )
        .join('\n');

    return '''
class _${model.className}Table extends StatelessWidget {
  const _${model.className}Table();

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: DataTable(
        columns: const [
$columns
        ],
        rows: const [],
      ),
    );
  }
}
''';
  }

  String _generateForm(AdminModel model) {
    final fields = model.fields.map(_generateInput).join('\n');

    return '''
class _${model.className}Form extends StatelessWidget {
  const _${model.className}Form();

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
$fields
        const SizedBox(height: 16),
        FilledButton(
          onPressed: null,
          child: Text('Save ${_escapeDart(_splitWords(model.className))}'),
        ),
      ],
    );
  }
}
''';
  }

  String _generateInput(AdminField field) {
    final label = _escapeDart(field.label);
    final unsupportedText = _escapeDart('${field.rawType} not supported yet');
    return switch (field.kind) {
      AdminFieldKind.text =>
        '''
        TextFormField(
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFieldKind.integer =>
        '''
        TextFormField(
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFieldKind.decimal =>
        '''
        TextFormField(
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFieldKind.boolean =>
        '''
        SwitchListTile(
          value: false,
          onChanged: null,
          title: Text('$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFieldKind.dateTime =>
        '''
        TextFormField(
          readOnly: true,
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFieldKind.unsupported =>
        '''
        InputDecorator(
          decoration: const InputDecoration(labelText: '$label'),
          child: Text('$unsupportedText'),
        ),
        const SizedBox(height: 12),''',
    };
  }
}

String _lowerFirst(String value) {
  if (value.isEmpty) {
    return value;
  }
  return value[0].toLowerCase() + value.substring(1);
}

String _pluralize(String value) {
  if (value.endsWith('y')) {
    return '${value.substring(0, value.length - 1)}ies';
  }
  if (value.endsWith('s')) {
    return value;
  }
  return '${value}s';
}

String _kebabCase(String value) {
  return value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)}-${match.group(2)}',
      )
      .replaceAll(RegExp(r'[\s_]+'), '-')
      .toLowerCase();
}

String _splitWords(String value) {
  final spaced = value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)} ${match.group(2)}',
      )
      .replaceAll('_', ' ');
  return spaced[0].toUpperCase() + spaced.substring(1);
}

String _escapeDart(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
