import 'package:yaml/yaml.dart';

class AdminModel {
  const AdminModel({
    required this.className,
    required this.fields,
    this.tableName,
  });

  final String className;
  final String? tableName;
  final List<AdminField> fields;

  String get variableName => _lowerFirst(className);
  String get title => _pluralize(_splitWords(className));
  String get routeName => '/admin/${_kebabCase(_pluralize(className))}';
}

class AdminField {
  const AdminField({required this.name, required this.rawType});

  final String name;
  final String rawType;

  String get dartType => rawType.replaceAll('?', '').trim();
  bool get isNullable => rawType.trim().endsWith('?');
  bool get isRequired => !isNullable;
  String get label => _splitWords(name);
  String get normalizedName => name.toLowerCase();
  String get htmlId => _kebabCase(name);

  AdminFieldKind get kind {
    return switch (dartType) {
      'String' => AdminFieldKind.text,
      'int' => AdminFieldKind.integer,
      'double' => AdminFieldKind.decimal,
      'bool' => AdminFieldKind.boolean,
      'DateTime' => AdminFieldKind.dateTime,
      _ => AdminFieldKind.unsupported,
    };
  }

  AdminFormControl get formControl {
    if (_isRelationLikeName(name)) {
      return AdminFormControl.relationSelect;
    }

    if (_isArrayLikeType(dartType)) {
      return AdminFormControl.arrayList;
    }

    if (_isEnumLikeType(dartType)) {
      return AdminFormControl.enumSelect;
    }

    if (kind == AdminFieldKind.text && _isLongTextName(name)) {
      return AdminFormControl.textarea;
    }

    return switch (kind) {
      AdminFieldKind.text => AdminFormControl.text,
      AdminFieldKind.integer => AdminFormControl.integer,
      AdminFieldKind.decimal => AdminFormControl.decimal,
      AdminFieldKind.boolean => AdminFormControl.checkbox,
      AdminFieldKind.dateTime => AdminFormControl.dateTime,
      AdminFieldKind.unsupported => AdminFormControl.unsupported,
    };
  }
}

enum AdminFieldKind { text, integer, decimal, boolean, dateTime, unsupported }

enum AdminFormControl {
  text,
  textarea,
  integer,
  decimal,
  checkbox,
  dateTime,
  enumSelect,
  relationSelect,
  arrayList,
  unsupported,
}

class AdminGenerator {
  const AdminGenerator();

  AdminModel parseModel(String yamlSource) {
    final document = loadYaml(yamlSource);
    if (document is! YamlMap) {
      throw const FormatException('Model YAML must be a map.');
    }

    final className = document['class'];
    if (className is! String || className.trim().isEmpty) {
      throw const FormatException('Model YAML must contain a class name.');
    }

    final fieldsNode = document['fields'];
    if (fieldsNode is! YamlMap || fieldsNode.isEmpty) {
      throw const FormatException('Model YAML must contain fields.');
    }

    final fields = <AdminField>[];
    for (final entry in fieldsNode.entries) {
      final name = entry.key;
      final type = entry.value;
      if (name is! String || name.trim().isEmpty) {
        throw const FormatException('Field names must be strings.');
      }
      if (type is! String || type.trim().isEmpty) {
        throw FormatException('Field "$name" must have a scalar type.');
      }
      fields.add(AdminField(name: name, rawType: type));
    }

    final tableName = document['table'];
    return AdminModel(
      className: className.trim(),
      tableName: tableName is String ? tableName.trim() : null,
      fields: fields,
    );
  }

  String generateFlutterSource(AdminModel model) {
    final buffer = StringBuffer()
      ..writeln(
        '// Generated by PocketPod admin generator. Do not edit by hand.',
      )
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln('class ${model.className}AdminScreen extends StatelessWidget {')
      ..writeln('  const ${model.className}AdminScreen({super.key});')
      ..writeln()
      ..writeln("  static const title = '${_escapeDart(model.title)}';")
      ..writeln("  static const routeName = '${_escapeDart(model.routeName)}';")
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Widget build(BuildContext context) {')
      ..writeln('    return Scaffold(')
      ..writeln('      appBar: AppBar(title: const Text(title)),')
      ..writeln('      body: ListView(')
      ..writeln('        padding: const EdgeInsets.all(24),')
      ..writeln('        children: [')
      ..writeln('          _${model.className}Table(),')
      ..writeln('          SizedBox(height: 24),')
      ..writeln('          _${model.className}Form(),')
      ..writeln('        ],')
      ..writeln('      ),')
      ..writeln('    );')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..write(_generateTable(model))
      ..writeln()
      ..write(_generateForm(model));

    return buffer.toString();
  }

  String adminFileName(AdminModel model) {
    return '${_snakeCase(model.className)}_admin.dart';
  }

  String get adminMetadataFileName => 'generated_admin_collections.dart';

  String generateFlutterMetadataSource(List<AdminModel> models) {
    final sortedModels = [...models]
      ..sort((left, right) => left.className.compareTo(right.className));
    final collections = sortedModels
        .map(_generateCollectionMetadata)
        .join(',\n');

    return '''
// Generated by PocketPod admin generator. Do not edit by hand.

class GeneratedAdminCollection {
  const GeneratedAdminCollection({
    required this.key,
    required this.title,
    required this.routeName,
    required this.fields,
  });

  final String key;
  final String title;
  final String routeName;
  final List<GeneratedAdminField> fields;
}

class GeneratedAdminField {
  const GeneratedAdminField({
    required this.name,
    required this.label,
    required this.dartType,
    required this.control,
    required this.required,
  });

  final String name;
  final String label;
  final String dartType;
  final String control;
  final bool required;
}

const generatedAdminCollections = <GeneratedAdminCollection>[
$collections
];
''';
  }

  String generatePreviewHtml(List<AdminModel> models) {
    final firstModel = models.isNotEmpty ? models.first : null;
    final navItems = models
        .map((model) {
          final activeClass = model == firstModel ? ' active' : '';
          return '''
        <button class="nav-item$activeClass">
          <span class="nav-dot"></span>
          <span>${_escapeHtml(model.title)}</span>
          <strong>${model.fields.length}</strong>
        </button>''';
        })
        .join('\n');

    final content = firstModel == null
        ? '<main class="content"><h1>No Models</h1></main>'
        : _previewContent(firstModel);

    return '''
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PocketPod Admin Preview</title>
  <style>
    :root {
      color-scheme: light;
      --ink: #1f2937;
      --muted: #6b7280;
      --soft: #8a94a6;
      --line: #d9e0ea;
      --panel: #ffffff;
      --surface: #f6f8fb;
      --sidebar: #eef3f8;
      --sidebar-line: #d7e1eb;
      --accent: #4fb7bf;
      --accent-soft: #e4f7f8;
      --accent-strong: #267d86;
      --danger: #ef5350;
      --success: #1c9b67;
      --shadow: 0 10px 30px rgba(31, 41, 55, 0.08);
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      min-height: 100vh;
      font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background: var(--surface);
    }
    .shell {
      display: grid;
      grid-template-columns: 260px minmax(0, 1fr);
      min-height: 100vh;
    }
    .sidebar {
      background: var(--sidebar);
      color: var(--ink);
      padding: 20px 14px;
      border-right: 1px solid var(--sidebar-line);
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 10px;
      height: 44px;
      padding: 0 8px;
      margin-bottom: 20px;
      font-weight: 800;
      letter-spacing: 0;
    }
    .brand-mark {
      display: grid;
      place-items: center;
      width: 34px;
      height: 34px;
      border-radius: 8px;
      color: #ffffff;
      background: linear-gradient(135deg, var(--accent), var(--accent-strong));
      box-shadow: 0 8px 18px rgba(79, 183, 191, 0.28);
      font-weight: 900;
    }
    .nav-label {
      padding: 0 10px;
      margin: 8px 0;
      color: var(--soft);
      font-size: 11px;
      font-weight: 800;
      letter-spacing: 0.08em;
      text-transform: uppercase;
    }
    .nav-item {
      display: grid;
      grid-template-columns: 10px minmax(0, 1fr) auto;
      align-items: center;
      gap: 10px;
      width: 100%;
      height: 40px;
      padding: 0 11px;
      margin-bottom: 5px;
      border: 1px solid transparent;
      border-radius: 9px;
      color: #445064;
      background: transparent;
      text-align: left;
      font: inherit;
      font-weight: 650;
    }
    .nav-dot {
      width: 8px;
      height: 8px;
      border-radius: 999px;
      background: #aab7c8;
    }
    .nav-item strong {
      min-width: 24px;
      height: 22px;
      padding: 2px 7px;
      border-radius: 999px;
      color: #667387;
      background: #dce6f0;
      font-size: 12px;
      text-align: center;
    }
    .nav-item.active {
      color: var(--accent-strong);
      background: #ffffff;
      border-color: #c2e7eb;
      box-shadow: 0 6px 16px rgba(31, 41, 55, 0.08);
    }
    .nav-item.active .nav-dot { background: var(--accent); }
    .nav-item.active strong {
      color: #ffffff;
      background: var(--accent);
    }
    .content {
      padding: 26px 30px;
    }
    .toolbar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      margin-bottom: 20px;
    }
    h1 {
      margin: 0;
      font-size: 25px;
      line-height: 1.2;
      letter-spacing: 0;
    }
    .crumb {
      margin-bottom: 6px;
      color: var(--soft);
      font-size: 13px;
      font-weight: 700;
    }
    .meta {
      margin-top: 4px;
      color: var(--muted);
    }
    .button {
      height: 38px;
      padding: 0 14px;
      border: 0;
      border-radius: 8px;
      color: #ffffff;
      background: #111827;
      font-weight: 700;
      box-shadow: 0 8px 18px rgba(17, 24, 39, 0.16);
    }
    .button.secondary {
      color: var(--accent-strong);
      background: var(--accent-soft);
      box-shadow: none;
    }
    .actions {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .layout {
      display: grid;
      grid-template-columns: minmax(0, 1.42fr) minmax(340px, 0.58fr);
      gap: 20px;
    }
    .panel {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 12px;
      overflow: hidden;
      box-shadow: var(--shadow);
    }
    .panel-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      min-height: 58px;
      padding: 13px 15px;
      border-bottom: 1px solid var(--line);
      background: #ffffff;
    }
    .panel-title {
      font-weight: 800;
    }
    .search {
      min-width: 260px;
      height: 36px;
      padding: 0 12px;
      border: 1px solid var(--line);
      border-radius: 8px;
      color: var(--muted);
      background: #f8fafc;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th, td {
      padding: 13px 14px;
      border-bottom: 1px solid var(--line);
      text-align: left;
      white-space: nowrap;
    }
    th {
      color: #697386;
      background: #f8fafc;
      font-size: 11px;
      font-weight: 800;
      text-transform: uppercase;
    }
    tr:last-child td { border-bottom: 0; }
    .form {
      padding: 16px;
    }
    .field {
      margin-bottom: 12px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      color: #384255;
      font-weight: 700;
    }
    .input {
      display: flex;
      align-items: center;
      min-height: 38px;
      padding: 0 11px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #f9fbfd;
      color: var(--muted);
    }
    textarea.input {
      display: block;
      width: 100%;
      min-height: 96px;
      padding: 10px 11px;
      resize: vertical;
      font: inherit;
    }
    input.input,
    select.input {
      width: 100%;
      font: inherit;
    }
    .checkbox-row {
      display: flex;
      align-items: center;
      gap: 10px;
      min-height: 38px;
      padding: 0 11px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #f9fbfd;
      color: var(--muted);
    }
    .checkbox-row input {
      width: 16px;
      height: 16px;
      accent-color: var(--accent-strong);
    }
    .required {
      color: var(--danger);
      font-weight: 900;
    }
    .optional {
      margin-left: 6px;
      color: var(--soft);
      font-size: 12px;
      font-weight: 650;
    }
    .hint {
      margin-top: 5px;
      color: var(--soft);
      font-size: 12px;
    }
    .pill {
      display: inline-flex;
      align-items: center;
      height: 24px;
      padding: 0 8px;
      border-radius: 999px;
      color: #ffffff;
      background: var(--accent-strong);
      font-size: 12px;
      font-weight: 700;
    }
    @media (max-width: 860px) {
      .shell { grid-template-columns: 1fr; }
      .sidebar { min-height: auto; }
      .layout { grid-template-columns: 1fr; }
    }
  </style>
</head>
<body>
  <div class="shell">
    <aside class="sidebar">
      <div class="brand">
        <div class="brand-mark">P</div>
        <span>PocketPod Admin</span>
      </div>
      <div class="nav-label">Collections</div>
$navItems
    </aside>
$content
  </div>
</body>
</html>
''';
  }

  String _previewContent(AdminModel model) {
    final headings = model.fields
        .map((field) => '<th>${_escapeHtml(field.label)}</th>')
        .join();
    final cells = model.fields.map((field) {
      final value = switch (field.formControl) {
        AdminFormControl.checkbox => '<span class="pill">Enabled</span>',
        AdminFormControl.integer => '42',
        AdminFormControl.decimal => '129.00',
        AdminFormControl.dateTime => '2026-06-30 09:30',
        AdminFormControl.textarea => 'Long text...',
        AdminFormControl.enumSelect => 'Published',
        AdminFormControl.relationSelect => 'Featured category',
        AdminFormControl.arrayList => 'news, launch',
        AdminFormControl.text => 'Sample ${_escapeHtml(field.label)}',
        AdminFormControl.unsupported => _escapeHtml(field.rawType),
      };
      return '<td>$value</td>';
    }).join();
    final fields = model.fields.map(_generatePreviewField).join('\n');

    return '''
    <main class="content">
      <div class="toolbar">
        <div>
          <div class="crumb">Collections / ${_escapeHtml(model.title)}</div>
          <h1>${_escapeHtml(model.title)}</h1>
          <div class="meta">${_escapeHtml(model.className)} model · ${model.fields.length} fields · admin scope required</div>
        </div>
        <div class="actions">
          <button class="button secondary">API preview</button>
          <button class="button">New ${_escapeHtml(_splitWords(model.className))}</button>
        </div>
      </div>
      <div class="layout">
        <section class="panel">
          <div class="panel-header">
            <div class="panel-title">Records</div>
            <div class="search">Search ${_escapeHtml(model.title)}...</div>
          </div>
          <table>
            <thead><tr>$headings</tr></thead>
            <tbody><tr>$cells</tr></tbody>
          </table>
        </section>
        <section class="panel form">
          <div class="panel-title">Edit ${_escapeHtml(_splitWords(model.className))}</div>
          <div style="height: 14px"></div>
$fields
          <button class="button">Save ${_escapeHtml(_splitWords(model.className))}</button>
        </section>
      </div>
    </main>''';
  }

  String _generatePreviewField(AdminField field) {
    final id = _escapeHtml(field.htmlId);
    final label = _previewLabel(field);
    final hint = _previewHint(field);
    final control = switch (field.formControl) {
      AdminFormControl.text =>
        '''
            <input id="$id" class="input" type="text" placeholder="${_escapeHtml(field.label)}">''',
      AdminFormControl.textarea =>
        '''
            <textarea id="$id" class="input" placeholder="${_escapeHtml(field.label)} details"></textarea>''',
      AdminFormControl.integer =>
        '''
            <input id="$id" class="input" type="number" step="1" placeholder="0">''',
      AdminFormControl.decimal =>
        '''
            <input id="$id" class="input" type="number" step="0.01" placeholder="0.00">''',
      AdminFormControl.checkbox =>
        '''
            <label class="checkbox-row" for="$id">
              <input id="$id" type="checkbox" checked>
              <span>${_escapeHtml(field.label)}</span>
            </label>''',
      AdminFormControl.dateTime =>
        '''
            <input id="$id" class="input" type="datetime-local" value="2026-06-30T09:30">''',
      AdminFormControl.enumSelect =>
        '''
            <select id="$id" class="input">
              <option>Draft</option>
              <option selected>Published</option>
              <option>Archived</option>
            </select>''',
      AdminFormControl.relationSelect =>
        '''
            <select id="$id" class="input">
              <option selected>Select ${_escapeHtml(_relationLabel(field.name))}</option>
              <option>Featured ${_escapeHtml(_relationLabel(field.name))}</option>
              <option>Default ${_escapeHtml(_relationLabel(field.name))}</option>
            </select>''',
      AdminFormControl.arrayList =>
        '''
            <input id="$id" class="input" type="text" value="news, launch, featured">''',
      AdminFormControl.unsupported =>
        '''
            <div id="$id" class="input">${_escapeHtml(field.rawType)} not supported yet</div>''',
    };

    return '''
          <div class="field">
            $label
$control
            $hint
          </div>''';
  }

  String _previewLabel(AdminField field) {
    final marker = field.isRequired
        ? '<span class="required">*</span>'
        : '<span class="optional">optional</span>';
    return '<label for="${_escapeHtml(field.htmlId)}">${_escapeHtml(field.label)} $marker</label>';
  }

  String _previewHint(AdminField field) {
    final text = switch (field.formControl) {
      AdminFormControl.textarea => 'Long text field',
      AdminFormControl.checkbox => 'Boolean field',
      AdminFormControl.dateTime => 'Date and time field',
      AdminFormControl.enumSelect => 'Enum or finite choice field',
      AdminFormControl.relationSelect =>
        'Relation or foreign-key lookup placeholder',
      AdminFormControl.arrayList => 'Array/list placeholder',
      AdminFormControl.integer => 'Integer number field',
      AdminFormControl.decimal => 'Decimal number field',
      AdminFormControl.text => 'Short text field',
      AdminFormControl.unsupported => 'Unsupported type',
    };
    return '<div class="hint">${_escapeHtml(text)}</div>';
  }

  String _generateTable(AdminModel model) {
    final columns = model.fields
        .map(
          (field) =>
              "          DataColumn(label: Text('${_escapeDart(field.label)}')),",
        )
        .join('\n');

    return '''
class _${model.className}Table extends StatelessWidget {
  const _${model.className}Table();

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: DataTable(
        columns: const [
$columns
        ],
        rows: const [],
      ),
    );
  }
}
''';
  }

  String _generateForm(AdminModel model) {
    final fields = model.fields.map(_generateInput).join('\n');

    return '''
class _${model.className}Form extends StatelessWidget {
  const _${model.className}Form();

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
$fields
        const SizedBox(height: 16),
        FilledButton(
          onPressed: null,
          child: Text('Save ${_escapeDart(_splitWords(model.className))}'),
        ),
      ],
    );
  }
}
''';
  }

  String _generateCollectionMetadata(AdminModel model) {
    final fields = model.fields.map(_generateFieldMetadata).join(',\n');
    return '''
  GeneratedAdminCollection(
    key: '${_escapeDart(_snakeCase(model.className))}',
    title: '${_escapeDart(model.title)}',
    routeName: '${_escapeDart(model.routeName)}',
    fields: [
$fields
    ],
  )''';
  }

  String _generateFieldMetadata(AdminField field) {
    return '''
      GeneratedAdminField(
        name: '${_escapeDart(field.name)}',
        label: '${_escapeDart(field.label)}',
        dartType: '${_escapeDart(field.rawType)}',
        control: '${_runtimeControlName(field.formControl)}',
        required: ${field.isRequired},
      )''';
  }

  String _runtimeControlName(AdminFormControl control) {
    return switch (control) {
      AdminFormControl.text => 'text',
      AdminFormControl.textarea => 'textarea',
      AdminFormControl.integer || AdminFormControl.decimal => 'number',
      AdminFormControl.checkbox => 'checkbox',
      AdminFormControl.dateTime => 'datetime',
      AdminFormControl.enumSelect => 'select',
      AdminFormControl.relationSelect => 'relation',
      AdminFormControl.arrayList => 'list',
      AdminFormControl.unsupported => 'unsupported',
    };
  }

  String _generateInput(AdminField field) {
    final label = _escapeDart(
      field.isRequired ? '${field.label} *' : '${field.label} (optional)',
    );
    final unsupportedText = _escapeDart('${field.rawType} not supported yet');
    return switch (field.formControl) {
      AdminFormControl.text =>
        '''
        TextFormField(
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.textarea =>
        '''
        TextFormField(
          minLines: 4,
          maxLines: 8,
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.integer =>
        '''
        TextFormField(
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.decimal =>
        '''
        TextFormField(
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
          decoration: const InputDecoration(labelText: '$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.checkbox =>
        '''
        CheckboxListTile(
          value: false,
          onChanged: null,
          title: Text('$label'),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.dateTime =>
        '''
        TextFormField(
          readOnly: true,
          decoration: const InputDecoration(
            labelText: '$label',
            suffixIcon: Icon(Icons.calendar_today),
          ),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.enumSelect =>
        '''
        DropdownButtonFormField<String>(
          decoration: const InputDecoration(labelText: '$label'),
          items: const [
            DropdownMenuItem(value: 'draft', child: Text('Draft')),
            DropdownMenuItem(value: 'published', child: Text('Published')),
            DropdownMenuItem(value: 'archived', child: Text('Archived')),
          ],
          onChanged: null,
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.relationSelect =>
        '''
        DropdownButtonFormField<String>(
          decoration: const InputDecoration(labelText: '$label'),
          items: const [
            DropdownMenuItem(value: 'sample', child: Text('Select related record')),
          ],
          onChanged: null,
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.arrayList =>
        '''
        TextFormField(
          decoration: const InputDecoration(
            labelText: '$label',
            helperText: 'Comma-separated values until array editor is implemented',
          ),
        ),
        const SizedBox(height: 12),''',
      AdminFormControl.unsupported =>
        '''
        InputDecorator(
          decoration: const InputDecoration(labelText: '$label'),
          child: Text('$unsupportedText'),
        ),
        const SizedBox(height: 12),''',
    };
  }
}

String _lowerFirst(String value) {
  if (value.isEmpty) {
    return value;
  }
  return value[0].toLowerCase() + value.substring(1);
}

String _pluralize(String value) {
  if (value.endsWith('y')) {
    return '${value.substring(0, value.length - 1)}ies';
  }
  if (value.endsWith('s')) {
    return value;
  }
  return '${value}s';
}

String _kebabCase(String value) {
  return value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)}-${match.group(2)}',
      )
      .replaceAll(RegExp(r'[\s_]+'), '-')
      .toLowerCase();
}

String _snakeCase(String value) {
  return value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)}_${match.group(2)}',
      )
      .replaceAll(RegExp(r'[\s-]+'), '_')
      .toLowerCase();
}

bool _isLongTextName(String value) {
  const longTextNames = {
    'body',
    'content',
    'description',
    'excerpt',
    'notes',
    'summary',
    'details',
    'bio',
  };
  return longTextNames.contains(value.toLowerCase());
}

bool _isRelationLikeName(String value) {
  final lower = value.toLowerCase();
  return lower.endsWith('id') &&
      lower.length > 2 &&
      !{'id', 'uuid'}.contains(lower);
}

bool _isArrayLikeType(String value) {
  return value.startsWith('List<') ||
      value.startsWith('Set<') ||
      value.startsWith('Map<');
}

bool _isEnumLikeType(String value) {
  const scalarTypes = {'String', 'int', 'double', 'bool', 'DateTime'};
  if (scalarTypes.contains(value) || _isArrayLikeType(value)) {
    return false;
  }
  return RegExp(r'^[A-Z][A-Za-z0-9_]*$').hasMatch(value) || value.contains(':');
}

String _relationLabel(String fieldName) {
  final withoutId = fieldName.toLowerCase().endsWith('id')
      ? fieldName.substring(0, fieldName.length - 2)
      : fieldName;
  return _splitWords(withoutId).toLowerCase();
}

String _splitWords(String value) {
  final spaced = value
      .replaceAllMapped(
        RegExp(r'([a-z0-9])([A-Z])'),
        (match) => '${match.group(1)} ${match.group(2)}',
      )
      .replaceAll('_', ' ');
  return spaced[0].toUpperCase() + spaced.substring(1);
}

String _escapeDart(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}

String _escapeHtml(String value) {
  return value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}
