# Local development configuration.

apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

database:
  filePath: .serverpod/development/database.sqlite
  maxConnectionCount: 5

maxRequestSize: 524288 # The maximum size of requests allowed in bytes

sessionLogs:
  persistentEnabled: false
  consoleEnabled: true
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"

# futureCallExecutionEnabled: true # Defaults to true

#futureCall:
#  concurrencyLimit: 1 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Unit in milliseconds, defaults to 5000
