#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STARTER_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
SERVER_DIR="$STARTER_DIR/pocketpod_server"
RELEASE_DIR="${1:-$STARTER_DIR/build/pocketpod-release}"
CLI_BUILD_DIR="$SERVER_DIR/build/pocketpod_release_cli"
API_URL="${POCKETPOD_API_URL:-http://localhost:8080/}"

rm -rf "$RELEASE_DIR" "$CLI_BUILD_DIR"
mkdir -p "$RELEASE_DIR"

echo "Building Flutter admin for Serverpod static hosting..."
POCKETPOD_API_URL="$API_URL" "$STARTER_DIR/tool/admin_ui/build_serverpod_admin.sh"

echo "Building Serverpod CLI bundle with native SQLite assets..."
(
  cd "$SERVER_DIR"
  dart build cli --target bin/main.dart --output "$CLI_BUILD_DIR"
)

echo "Assembling release artifact at $RELEASE_DIR..."
cp -R "$CLI_BUILD_DIR/bundle/." "$RELEASE_DIR/"

mkdir -p \
  "$RELEASE_DIR/config" \
  "$RELEASE_DIR/migrations" \
  "$RELEASE_DIR/web" \
  "$RELEASE_DIR/.serverpod/production" \
  "$RELEASE_DIR/logs"

rsync -a --exclude 'passwords.yaml' "$SERVER_DIR/config/" "$RELEASE_DIR/config/"
rsync -a "$SERVER_DIR/migrations/" "$RELEASE_DIR/migrations/"
rsync -a "$SERVER_DIR/web/" "$RELEASE_DIR/web/"

cat > "$RELEASE_DIR/README.md" <<'README'
# PocketPod Release Artifact

This directory is generated by `tool/deploy/build_release.sh`.

Layout:

```text
bin/main        compiled PocketPod Serverpod executable
lib/            native SQLite dynamic libraries required by the executable
config/         Serverpod config files; copy template.passwords.yaml to passwords.yaml before production use
migrations/     Serverpod migration files
web/            static web assets, including the Flutter admin app at /app/
.serverpod/     local SQLite runtime directory
logs/           local runtime logs
```

Production startup shape:

```sh
cp config/template.passwords.yaml config/passwords.yaml
# edit config/passwords.yaml with real deployment secrets
./bin/main --mode production --apply-migrations
```

Smoke-test this artifact from the repository root with:

```sh
tool/deploy/smoke_release.sh
```
README

cat > "$RELEASE_DIR/MANIFEST.txt" <<MANIFEST
PocketPod release artifact
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Host: $(uname -s)-$(uname -m)
API URL used for admin build: $API_URL
Server executable: bin/main
Admin app path: web/app
SQLite production database path: .serverpod/production/database.sqlite
MANIFEST

echo "Release artifact ready:"
find "$RELEASE_DIR" -maxdepth 2 -type f | sort
